site_name: DSE StarChaser
site_url: https://louiskwt.github.io/starchaser-portal/
site_description: A free and open-source study guide for DSE English Learning

theme:
  name: material
  logo: assets/icon-196.png
  favicon: assets/icon-196.png
  palette:
    primary: black
    scheme: slate

nav:
  - Resources: resources/index.md
  - Grammar Lessons:
      - grammar/index.md
