site_name: DSE StarChaser
site_url: https://dsestarchaser.me/
site_description: A free and open-source study guide for DSE English Learning

theme:
  name: material
  logo: assets/icon-196.png
  favicon: assets/icon-196.png
  palette:
    primary: black
    scheme: slate

nav:
  - Home: index.md
  - Resources: resources/index.md
  - Grammar Lessons:
      - grammar/index.md
  - Writing Lessons:
      - writing/index.md
      - Samples:
        - writing/samples/2019_partA.md
        - writing/samples/dse_2019_part_B_2.md
        - writing/samples/2021_partA.md
        - writing/samples/2021_partB_2.md
  - Listening Lessons:
      - listening/index.md
  - Speaking Notes: speaking/index.md
