# Generated by Django 4.2.7 on 2023-11-14 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_alter_quiz_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="vocab_list",
            field=models.TextField(null=True, blank=True)
        ),
    ]
