# Generated by Django 4.2.7 on 2023-11-19 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_quiz_vocab_list"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="answer_key",
            field=models.TextField(blank=True, null=True),
        ),
    ]
