name: Deploy to Netlify

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Install Netlify
        uses: borales/actions-yarn@v4
        with:
          cmd: add netlify-cli -g
      - name: Build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          ntl deploy --prod \
            --dir dist \
            --site ${{ secrets.NETLIFY_SITE_ID }} \
            --auth ${{ secrets.NETLIFY_API_TOKEN }}
